#LB grafana
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9093
  selector:
    app: alertmanager
  type: LoadBalancer