# Roteamento da porta para  o container - usar o prometheus fora do container.
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus
  type: LoadBalancer